export interface Course {
  id: string;
  title: string;
  description: string;
  instructor: string;
  instructorAvatar: string;
  category: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  duration: string;
  lessons: number;
  rating: number;
  students: number;
  price: number;
  thumbnail: string;
  tags: string[];
  youtubeId?: string;
  curriculum: { title: string; duration: string }[];
}

export const CATEGORIES = [
  "All",
  "Web Development",
  "Data Science",
  "AI & ML",
  "Mobile Dev",
  "Design",
  "DevOps",
  "Cybersecurity",
  "Blockchain",
  "Cloud Computing",
];

export const COURSES: Course[] = [
  {
    id: "c1",
    title: "Complete React & Next.js Masterclass",
    description: "Master React 18, Next.js 14, TypeScript, and modern web development patterns from scratch to advanced.",
    instructor: "Sarah Johnson",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=sarah",
    category: "Web Development",
    level: "Intermediate",
    duration: "42 hours",
    lessons: 156,
    rating: 4.9,
    students: 28450,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/wm5gMKuwSYk/maxresdefault.jpg",
    youtubeId: "wm5gMKuwSYk",
    tags: ["React", "Next.js", "TypeScript", "Frontend"],
    curriculum: [
      { title: "React Fundamentals", duration: "4h 30m" },
      { title: "Hooks Deep Dive", duration: "5h 15m" },
      { title: "Next.js App Router", duration: "6h 00m" },
      { title: "State Management", duration: "4h 45m" },
      { title: "Performance Optimization", duration: "3h 30m" },
    ],
  },
  {
    id: "c2",
    title: "Python for Data Science & ML",
    description: "Learn Python, NumPy, Pandas, Matplotlib, Scikit-learn, and build real ML models with hands-on projects.",
    instructor: "Dr. Raj Patel",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=raj",
    category: "Data Science",
    level: "Beginner",
    duration: "38 hours",
    lessons: 142,
    rating: 4.8,
    students: 45200,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/LHBE6Q9XlzI/maxresdefault.jpg",
    youtubeId: "LHBE6Q9XlzI",
    tags: ["Python", "ML", "Data Science", "Pandas"],
    curriculum: [
      { title: "Python Basics", duration: "5h 00m" },
      { title: "NumPy & Pandas", duration: "6h 30m" },
      { title: "Data Visualization", duration: "4h 00m" },
      { title: "Machine Learning Basics", duration: "8h 00m" },
      { title: "Deep Learning Intro", duration: "5h 30m" },
    ],
  },
  {
    id: "c3",
    title: "Full Stack Web3 & Blockchain Dev",
    description: "Build decentralized apps with Solidity, Ethereum, Hardhat, and integrate with React frontends.",
    instructor: "Alex Chen",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=alex",
    category: "Blockchain",
    level: "Advanced",
    duration: "35 hours",
    lessons: 128,
    rating: 4.7,
    students: 12300,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/gyMwXuJrbJQ/maxresdefault.jpg",
    youtubeId: "gyMwXuJrbJQ",
    tags: ["Blockchain", "Solidity", "Web3", "Ethereum"],
    curriculum: [
      { title: "Blockchain Fundamentals", duration: "4h 00m" },
      { title: "Solidity Programming", duration: "8h 00m" },
      { title: "Smart Contracts", duration: "6h 00m" },
      { title: "DApp Development", duration: "7h 00m" },
      { title: "DeFi Protocols", duration: "5h 00m" },
    ],
  },
  {
    id: "c4",
    title: "UI/UX Design with Figma",
    description: "Design stunning user interfaces and experiences using Figma, design systems, and prototyping.",
    instructor: "Priya Sharma",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=priya",
    category: "Design",
    level: "Beginner",
    duration: "28 hours",
    lessons: 98,
    rating: 4.9,
    students: 33100,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/FTFaQWZBqQ8/maxresdefault.jpg",
    youtubeId: "FTFaQWZBqQ8",
    tags: ["Figma", "UI/UX", "Design", "Prototyping"],
    curriculum: [
      { title: "Design Principles", duration: "3h 00m" },
      { title: "Figma Basics", duration: "4h 30m" },
      { title: "Component Systems", duration: "5h 00m" },
      { title: "Prototyping", duration: "4h 00m" },
      { title: "User Research", duration: "3h 30m" },
    ],
  },
  {
    id: "c5",
    title: "AWS Cloud Practitioner & Solutions Architect",
    description: "Master AWS services, cloud architecture, and prepare for AWS certification exams.",
    instructor: "Michael Torres",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=michael",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "45 hours",
    lessons: 168,
    rating: 4.8,
    students: 21800,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/3hLmDS179YE/maxresdefault.jpg",
    youtubeId: "3hLmDS179YE",
    tags: ["AWS", "Cloud", "DevOps", "Architecture"],
    curriculum: [
      { title: "Cloud Fundamentals", duration: "4h 00m" },
      { title: "AWS Core Services", duration: "8h 00m" },
      { title: "Security & IAM", duration: "5h 00m" },
      { title: "Networking & VPC", duration: "6h 00m" },
      { title: "Serverless & Lambda", duration: "5h 00m" },
    ],
  },
  {
    id: "c6",
    title: "Flutter & Dart Mobile Development",
    description: "Build beautiful cross-platform iOS and Android apps with Flutter, Dart, and Firebase integration.",
    instructor: "Aisha Williams",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=aisha",
    category: "Mobile Dev",
    level: "Intermediate",
    duration: "40 hours",
    lessons: 145,
    rating: 4.7,
    students: 18900,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/VPvVD8t02U8/maxresdefault.jpg",
    youtubeId: "VPvVD8t02U8",
    tags: ["Flutter", "Dart", "Mobile", "iOS", "Android"],
    curriculum: [
      { title: "Dart Programming", duration: "5h 00m" },
      { title: "Flutter Widgets", duration: "7h 00m" },
      { title: "State Management", duration: "5h 30m" },
      { title: "Firebase Integration", duration: "4h 00m" },
      { title: "App Deployment", duration: "3h 00m" },
    ],
  },
  {
    id: "c7",
    title: "Ethical Hacking & Cybersecurity",
    description: "Learn penetration testing, network security, vulnerability assessment, and ethical hacking techniques.",
    instructor: "James Rodriguez",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=james",
    category: "Cybersecurity",
    level: "Advanced",
    duration: "50 hours",
    lessons: 185,
    rating: 4.9,
    students: 15600,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/3Kq1MIfTWCE/maxresdefault.jpg",
    youtubeId: "3Kq1MIfTWCE",
    tags: ["Security", "Hacking", "Networking", "Kali Linux"],
    curriculum: [
      { title: "Security Fundamentals", duration: "5h 00m" },
      { title: "Network Scanning", duration: "6h 00m" },
      { title: "Web App Pentesting", duration: "8h 00m" },
      { title: "Exploitation Techniques", duration: "7h 00m" },
      { title: "Reporting & Defense", duration: "4h 00m" },
    ],
  },
  {
    id: "c8",
    title: "Deep Learning & Neural Networks",
    description: "Master TensorFlow, PyTorch, CNNs, RNNs, Transformers, and build production-ready AI models.",
    instructor: "Dr. Lisa Park",
    instructorAvatar: "https://api.dicebear.com/8.x/avataaars/svg?seed=lisa",
    category: "AI & ML",
    level: "Advanced",
    duration: "55 hours",
    lessons: 200,
    rating: 4.9,
    students: 22400,
    price: 0,
    thumbnail: "https://img.youtube.com/vi/aircAruvnKk/maxresdefault.jpg",
    youtubeId: "aircAruvnKk",
    tags: ["Deep Learning", "TensorFlow", "PyTorch", "AI"],
    curriculum: [
      { title: "Neural Network Basics", duration: "6h 00m" },
      { title: "CNNs for Vision", duration: "8h 00m" },
      { title: "RNNs & LSTMs", duration: "7h 00m" },
      { title: "Transformers & Attention", duration: "9h 00m" },
      { title: "Model Deployment", duration: "5h 00m" },
    ],
  },
];
